dataset_name: RepCount_pose
train_split: ['train']
test_split: ['test']
dataset: {
  dataset_root_dir: './RepCount_pose',
  csv_label_path: 'all_action.csv',
  batch_size: 16,
}
PoseRAC: {
  seed: 42,
  dim: 99,
  heads: 9, # default 9
  enc_layer: 6, # default 6
  all_key_points: 99,
  learning_rate: 0.00025, # default 0.00025
  alpha: 0.01
}
Action_trigger: {
  enter_threshold: 0.78,
  exit_threshold: 0.4,
  momentum: 0.4
}
trainer: {
  max_epochs: 20, # default 20
  auto_lr_find: True,
  accelerator: 'cpu',
  devices: 1
}
save_dir: 'saved_models'
